/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceCadastramentoPainelsAdministrativo;

import BancoDeDados.BancoDeDados;
import InterfaceMain.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author YiazmaT
 */
public class AjustarValorProdutos_Administrativo extends javax.swing.JPanel {
    private Main pai;
    /**
     * Creates new form AjustarValorProdutos_Administrativo
     */
    public AjustarValorProdutos_Administrativo(Main pai) {
        initComponents();
        this.pai=pai;
        elevar.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abaixar = new javax.swing.JRadioButton();
        elevar = new javax.swing.JRadioButton();
        porcentagemField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setOpaque(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/controls.png"))); // NOI18N
        jLabel1.setText("Ajustar o Valor de Todos os Produtos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Porcentagem:");

        abaixar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        abaixar.setText("Abaixar");
        abaixar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abaixarMouseClicked(evt);
            }
        });
        abaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abaixarActionPerformed(evt);
            }
        });

        elevar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elevar.setText("Elevar");
        elevar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elevarMouseClicked(evt);
            }
        });
        elevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elevarActionPerformed(evt);
            }
        });

        porcentagemField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("%");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/controls.png"))); // NOI18N
        jButton1.setText("Ajustar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentagemField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(elevar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(abaixar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abaixar)
                    .addComponent(elevar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentagemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, porcentagemField});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void elevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elevarActionPerformed
        abaixar.setSelected(false);
        elevar.setSelected(true);
    }//GEN-LAST:event_elevarActionPerformed

    private void elevarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elevarMouseClicked
        abaixar.setSelected(false);
        elevar.setSelected(true);
    }//GEN-LAST:event_elevarMouseClicked

    private void abaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abaixarActionPerformed
        abaixar.setSelected(true);
        elevar.setSelected(false);
    }//GEN-LAST:event_abaixarActionPerformed

    private void abaixarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abaixarMouseClicked
        abaixar.setSelected(true);
        elevar.setSelected(false);
    }//GEN-LAST:event_abaixarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(porcentagemField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor Insira uma Porcentagem!!");
            return;
        }
        float porcentagem = Float.parseFloat(porcentagemField.getText().replaceAll("\\,", "\\."));
        if(porcentagem <= 0){
            JOptionPane.showMessageDialog(null, "Não são permitidas quantidades negativas!!");
            return;
        }
        
        if(elevar.isSelected()){
            int confirm;
            confirm = JOptionPane.showConfirmDialog(null, "Deseja Realmente Aumentar o Valor de Todos os Produto em "+String.format("%.2f", porcentagem)+"%?"
                , "Atenção!!", JOptionPane.YES_NO_OPTION);
            if(confirm == 0){
                BancoDeDados.aumentarPreçoTodosOsProdutos(porcentagem);
            }
        }
        else{
            int confirm;
            confirm = JOptionPane.showConfirmDialog(null, "Deseja Realmente Abaixar o Valor de Todos os Produto em "+String.format("%.2f", porcentagem)+"%?"
                , "Atenção!!", JOptionPane.YES_NO_OPTION);
            if(confirm == 0){
                BancoDeDados.abaixarPreçoTodosOsProdutos(porcentagem);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abaixar;
    private javax.swing.JRadioButton elevar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField porcentagemField;
    // End of variables declaration//GEN-END:variables
}
