/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceCadastramentoPainelsAdministrativo;

import ClassesLojas.Loja;

/**
 *
 * @author YiazmaT
 */
public class PanelAuxiliarCadastrarFornecedor extends javax.swing.JPanel {
    private Loja loja;
    private NovoFornecedor_Administrativo pai;
    /**
     * Creates new form PanelAuxiliarCadastrarFornecedor
     */
    public PanelAuxiliarCadastrarFornecedor(NovoFornecedor_Administrativo pai, Loja loja) {
        initComponents();
        this.loja = loja;
        this.pai = pai;
        
        nomeLoja.setText(this.loja.getNome());
    }

    public Loja getLoja() {
        return this.loja;
    }
    
    public boolean isBotaoSelecionado(){
        if(selecionaLoja.isSelected() == true) return true;
        else return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeLoja = new javax.swing.JLabel();
        selecionaLoja = new javax.swing.JCheckBox();

        nomeLoja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nomeLoja, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecionaLoja))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(selecionaLoja)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nomeLoja;
    private javax.swing.JCheckBox selecionaLoja;
    // End of variables declaration//GEN-END:variables
}
