/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceVendas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YiazmaT
 */
public class PagamentoDialog extends javax.swing.JDialog {
    private Vendas pai;
    private ArrayList<Pagamento> pagamentosCartao = new ArrayList<Pagamento>();
    private float totalNota;
    private float totalRecebido;
    private float recebidoCartao;
    private float recebidoDinheiro;
    /**
     * Creates new form Pagamento
     */
    public PagamentoDialog(java.awt.Frame parent, boolean modal, Vendas pai, float totalNota) {
        super(parent, modal);
        initComponents();
        this.pai=pai;
        this.totalNota = totalNota;
        this.totalRecebido = 0.0f;
        
        this.travarPainelCartao();
        totalLabel.setText("R$"+String.format("%.2f", totalNota));
        totalRecebidoLabel.setText("R$"+String.format("%.2f", 0.0f));
        
        dinheiroButton.setSelected(true);
        creditoButton.setSelected(true);
        finalizarPagamentoButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cartaoButton = new javax.swing.JRadioButton();
        dinheiroButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cartaoPanel = new javax.swing.JPanel();
        creditoButton = new javax.swing.JRadioButton();
        debitoButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bandeiraField = new javax.swing.JTextField();
        u4digitosField = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        valorPagamentoField = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCartao = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        removerCartao = new javax.swing.JButton();
        totalCartaoField = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalRecebidoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        trocoLabel = new javax.swing.JLabel();
        finalizarPagamentoButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dinheiroRecebidoField = new javax.swing.JLabel();
        removerCartao1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aba de Pagamento");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        cartaoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cartaoButton.setText("Cartão");
        cartaoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaoButtonMouseClicked(evt);
            }
        });
        cartaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoButtonActionPerformed(evt);
            }
        });

        dinheiroButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dinheiroButton.setText("Dinheiro");
        dinheiroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dinheiroButtonMouseClicked(evt);
            }
        });
        dinheiroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Valor do Pagamento:");

        cartaoPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cartaoPanel.setToolTipText("");

        creditoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        creditoButton.setText("Crédito");
        creditoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditoButtonMouseClicked(evt);
            }
        });
        creditoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoButtonActionPerformed(evt);
            }
        });

        debitoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        debitoButton.setText("Débito");
        debitoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                debitoButtonMouseClicked(evt);
            }
        });
        debitoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitoButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cartão:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Últimos 4 Dígitos:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bandeira:");

        try {
            u4digitosField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout cartaoPanelLayout = new javax.swing.GroupLayout(cartaoPanel);
        cartaoPanel.setLayout(cartaoPanelLayout);
        cartaoPanelLayout.setHorizontalGroup(
            cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(cartaoPanelLayout.createSequentialGroup()
                        .addComponent(creditoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(debitoButton))
                    .addGroup(cartaoPanelLayout.createSequentialGroup()
                        .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bandeiraField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u4digitosField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartaoPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bandeiraField, u4digitosField});

        cartaoPanelLayout.setVerticalGroup(
            cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditoButton)
                    .addComponent(debitoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u4digitosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bandeiraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cartaoPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bandeiraField, jLabel4, u4digitosField});

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-square-button.png"))); // NOI18N
        jButton1.setText("Adicionar Pagamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        valorPagamentoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        valorPagamentoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPagamentoFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dinheiroButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cartaoButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorPagamentoField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinheiroButton)
                    .addComponent(cartaoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorPagamentoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cartaoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, valorPagamentoField});

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tabelaCartao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaCartao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Crédito ou Débito", "Últimos 4 Dígitos", "Bandeira"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCartao);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pagamentos em Cartão Recebidos:");

        removerCartao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removerCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-symbol.png"))); // NOI18N
        removerCartao.setText("Remover Cartão");
        removerCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCartaoActionPerformed(evt);
            }
        });

        totalCartaoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalCartaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(removerCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(totalCartaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerCartao)
                .addGap(101, 101, 101))
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total a ser Pago:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total Recebido:");

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLabel.setToolTipText("");

        totalRecebidoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalRecebidoLabel.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Troco:");

        trocoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trocoLabel.setToolTipText("");

        finalizarPagamentoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalizarPagamentoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/give-money.png"))); // NOI18N
        finalizarPagamentoButton.setText("Finalizar Pagamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalizarPagamentoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trocoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalRecebidoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, jLabel7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalRecebidoLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(trocoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalizarPagamentoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, jLabel6, jLabel7, totalLabel, totalRecebidoLabel, trocoLabel});

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Pagamento em Dinheiro Recebido:");

        removerCartao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removerCartao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remove-symbol.png"))); // NOI18N
        removerCartao1.setText("Remover Valor em Dinheiro");
        removerCartao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCartao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dinheiroRecebidoField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removerCartao1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dinheiroRecebidoField))
                    .addComponent(removerCartao1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dinheiroRecebidoField, jLabel9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dinheiroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroButtonActionPerformed
        dinheiroButton.setSelected(true);
        cartaoButton.setSelected(false);
        this.travarPainelCartao();
    }//GEN-LAST:event_dinheiroButtonActionPerformed

    private void creditoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoButtonActionPerformed
        creditoButton.setSelected(true);
        debitoButton.setSelected(false);
    }//GEN-LAST:event_creditoButtonActionPerformed

    private void dinheiroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dinheiroButtonMouseClicked
        dinheiroButton.setSelected(true);
        cartaoButton.setSelected(false);
        this.travarPainelCartao();
    }//GEN-LAST:event_dinheiroButtonMouseClicked

    private void cartaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoButtonActionPerformed
        dinheiroButton.setSelected(false);
        cartaoButton.setSelected(true);
        this.destravarPainelCartao();
    }//GEN-LAST:event_cartaoButtonActionPerformed

    private void cartaoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaoButtonMouseClicked
        dinheiroButton.setSelected(false);
        cartaoButton.setSelected(true);
        this.destravarPainelCartao();
    }//GEN-LAST:event_cartaoButtonMouseClicked

    private void creditoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditoButtonMouseClicked
        creditoButton.setSelected(true);
        debitoButton.setSelected(false);
    }//GEN-LAST:event_creditoButtonMouseClicked

    private void debitoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitoButtonActionPerformed
        creditoButton.setSelected(false);
        debitoButton.setSelected(true);
    }//GEN-LAST:event_debitoButtonActionPerformed

    private void debitoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_debitoButtonMouseClicked
        creditoButton.setSelected(false);
        debitoButton.setSelected(true);
    }//GEN-LAST:event_debitoButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //pegar e validar valor;
        if(valorPagamentoField.getText().equals("") || 0>Float.parseFloat(valorPagamentoField.getText().replaceAll("\\,", "\\."))){
                this.erro(1);
                return;
        }
        
        //dinheiro;
        if(dinheiroButton.isSelected()){
            this.recebidoDinheiro += Float.parseFloat(valorPagamentoField.getText().replaceAll("\\,", "\\."));
            this.totalRecebido += Float.parseFloat(valorPagamentoField.getText().replaceAll("\\,", "\\."));
            dinheiroRecebidoField.setText("R$"+String.format("%.2f", this.recebidoDinheiro));
            totalRecebidoLabel.setText("R$"+String.format("%.2f", this.totalRecebido));
            
            if(this.totalRecebido > this.totalNota){
                trocoLabel.setText("R$"+String.format("%.2f", this.totalRecebido-this.totalNota));
            }
        }
        //cartao
        else{
            //pegar e validar ultimos 4 digitos;
            String u4 = u4digitosField.getText();
            if(u4.contains(" ")){this.erro(2); return;}
            
            //pegar e validar bandeira;
            String bandeira = bandeiraField.getText();
            if(bandeira.equals("")) {this.erro(3); return;}
            if(bandeira.length() > 20){this.erro(4); return;}
            if(!bandeira.matches("([0-9a-zA-Z ]|â|à|ã|ä|á|Á|ê|ë|é|É|î|ï|í|Í|ô|õ|ö|ó|Ó|û|ü|ú|Ú|'|ç){1,20}")){this.erro(3); return;}
            
            //pegar e validar tipo;
            String tipo;
            if(creditoButton.isSelected()){
                tipo = "CRÉDITO";
            }
            else tipo = "DÉBITO";
            
            //criar pagamento com cartao;
            Pagamento p = new Pagamento(Float.parseFloat(valorPagamentoField.getText().replaceAll("\\,", "\\.")), true, Integer.parseInt(u4digitosField.getText()), bandeira, tipo);
            //addnar pagamento e atualizar tabela;
            this.pagamentosCartao.add(p);
            this.atualizarPagamentosCartao();
        }
        
        //resetar campos
        valorPagamentoField.setText("");
        u4digitosField.setText("");
        bandeiraField.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void removerCartao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCartao1ActionPerformed
        this.dinheiroRecebidoField.setText("R$0,00");
        this.totalRecebido -= this.recebidoDinheiro;
        this.recebidoDinheiro = 0.0f;
        this.totalRecebidoLabel.setText("R$"+String.format("%.2f", this.totalRecebido));
        trocoLabel.setText("R$0,00");
    }//GEN-LAST:event_removerCartao1ActionPerformed

    private void removerCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCartaoActionPerformed
        int linha = tabelaCartao.getSelectedRow();
        if(linha<0) return;
        
        this.pagamentosCartao.remove(linha);
        this.atualizarPagamentosCartao();
    }//GEN-LAST:event_removerCartaoActionPerformed

    private void valorPagamentoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPagamentoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPagamentoFieldActionPerformed

    private void erro(int e){
        switch(e){
            case 1: JOptionPane.showMessageDialog(null, "Valor de pagamento inválido!!"); break;
            case 2: JOptionPane.showMessageDialog(null, "Últimos 4 digitos inválidos!!"); break;
            case 3: JOptionPane.showMessageDialog(null, "Bandeira Inválida, utilize apenas letras!!"); break;
            case 4: JOptionPane.showMessageDialog(null, "Bandeira pode ter no máximo 20 caracteres!!"); break;
        }
    }
    
    private void travarPainelCartao(){
        cartaoPanel.setEnabled(false);
        creditoButton.setEnabled(false);
        debitoButton.setEnabled(false);
        u4digitosField.setEditable(false);
        bandeiraField.setEditable(false);
    }
    
    private void destravarPainelCartao(){
        cartaoPanel.setEnabled(true);
        creditoButton.setEnabled(true);
        debitoButton.setEnabled(true);
        u4digitosField.setEditable(true);
        bandeiraField.setEditable(true);
        u4digitosField.setText("");
        bandeiraField.setText("");
    }
    
    private void atualizarPagamentosCartao(){
        DefaultTableModel dtm = (DefaultTableModel) tabelaCartao.getModel();
        dtm.setRowCount(0);
        String [] linha = new String[4];
        
        recebidoCartao = 0.0f;
        
        for(Pagamento p : this.pagamentosCartao){
            linha[0] = String.format("%.2f",p.getValor());
            linha[1] = p.getTipo();
            linha[2] = String.valueOf(p.getUltimos4Digitos());
            linha[3] = p.getBandeira();
            recebidoCartao += p.getValor();
            dtm.addRow(linha);
        }
        
        this.totalRecebido = this.recebidoCartao+this.recebidoDinheiro;
        this.totalRecebidoLabel.setText("R$"+String.format("%.2f", this.totalRecebido));
        totalCartaoField.setText("R$"+String.format("%.2f", this.recebidoCartao));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bandeiraField;
    private javax.swing.JRadioButton cartaoButton;
    private javax.swing.JPanel cartaoPanel;
    private javax.swing.JRadioButton creditoButton;
    private javax.swing.JRadioButton debitoButton;
    private javax.swing.JRadioButton dinheiroButton;
    private javax.swing.JLabel dinheiroRecebidoField;
    private javax.swing.JButton finalizarPagamentoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removerCartao;
    private javax.swing.JButton removerCartao1;
    private javax.swing.JTable tabelaCartao;
    private javax.swing.JLabel totalCartaoField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalRecebidoLabel;
    private javax.swing.JLabel trocoLabel;
    private javax.swing.JFormattedTextField u4digitosField;
    private javax.swing.JFormattedTextField valorPagamentoField;
    // End of variables declaration//GEN-END:variables
}
