/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDialogsRelatorios;

import BancoDeDados.BancoDeDados;
import ClasseProdutos.ProdutoAtomico;
import ClassesLojas.Loja;
import InterfaceDialogsAlteracaoDeDados.ModificarEstoque;
import InterfaceMain.Main;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eymar Lima
 */
public class EstoqueLanchonetes extends javax.swing.JDialog {
    private Main pai;
    private ArrayList<Loja> lojas;
    private ArrayList<ProdutoAtomico> produtosTabela;
    private ArrayList<Integer> indiceIdLoja;
    /**
     * Creates new form EstoqueLanchonetes
     */
    public EstoqueLanchonetes(java.awt.Frame parent, boolean modal, ArrayList<Loja> lojas, Main pai) {
        super(parent, modal);
        initComponents();
        this.lojas = lojas;
        this.pai = pai;
        this.preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estoqueTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoques Atuais");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Estoques Atuais:");

        estoqueTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estoqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Produto Atômico", "Unidade de Medida", "Quantidade em Estoque", "Nome da Loja Referente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(estoqueTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shuffle (1).png"))); // NOI18N
        jButton1.setText("Alterar Quantidade em Estoque");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int linha = estoqueTable.getSelectedRow();
        if(linha < 0) return;
        
        //pegar loja ao qual o item pertence;
        for(Loja atual : lojas){
            if(atual.getId_lanchonete() == indiceIdLoja.get(linha)){
                ModificarEstoque m = new ModificarEstoque(this.pai, true, produtosTabela.get(linha), atual);
                m.setLocationRelativeTo(this.pai);
                m.setVisible(true);
                
                this.preencherTabela();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void preencherTabela(){
        DefaultTableModel dtm = (DefaultTableModel) estoqueTable.getModel();
        dtm.setRowCount(0);
        
        produtosTabela = new ArrayList<ProdutoAtomico>();
        indiceIdLoja = new ArrayList<Integer>();
        
        ArrayList<ProdutoAtomico> p;
        String [] linha = new String[4];
        for(Loja lojaAtual: lojas){
            p = BancoDeDados.estoqueDeUmaLoja(lojaAtual.getId_lanchonete());
            if(!p.isEmpty()){
                for(ProdutoAtomico pas : p){
                    this.indiceIdLoja.add(lojaAtual.getId_lanchonete());
                    this.produtosTabela.add(pas);
                    linha[0] = pas.getNome();
                    linha[1] = pas.getUnidade();
                    linha[2] = String.valueOf(pas.getQuantidade());
                    linha[3] = lojaAtual.getNome();
                    dtm.addRow(linha);
                }
            } 
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable estoqueTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
