/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDialogsRelatorios;

import BancoDeDados.BancoDeDados;
import ClassesFuncionarios.Caixa;
import ClassesFuncionarios.Cozinheiro;
import ClassesFuncionarios.Faxineiro;
import ClassesFuncionarios.Gerente;
import ClassesLojas.Loja;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eymar Lima
 */
public class RelatorioFuncionarios extends javax.swing.JDialog {
    private ArrayList<Loja> lojas;
    /**
     * Creates new form RelatorioFuncionarios
     */
    public RelatorioFuncionarios(java.awt.Frame parent, boolean modal, ArrayList<Loja> lojas) {
        super(parent, modal);
        initComponents();
        this.lojas = lojas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        funcionariosTable = new javax.swing.JTable();
        gerentesBox = new javax.swing.JCheckBox();
        caixasBox = new javax.swing.JCheckBox();
        auxiliarBox = new javax.swing.JCheckBox();
        cozinheirosBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        selecionaTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Funcionários");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Funcionários:");

        funcionariosTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        funcionariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "CPF", "Lanchonete", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(funcionariosTable);

        gerentesBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gerentesBox.setText("Gerentes");
        gerentesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerentesBoxActionPerformed(evt);
            }
        });

        caixasBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        caixasBox.setText("Caixas");

        auxiliarBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        auxiliarBox.setText("Auxiliares de Limpeza");

        cozinheirosBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cozinheirosBox.setText("Cozinheiros");
        cozinheirosBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cozinheirosBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/power (1).png"))); // NOI18N
        jButton1.setText("Gerar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecione os tipos de funcionário desejado:");

        selecionaTodos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selecionaTodos.setText("Selecionar Todos");
        selecionaTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecionaTodosMouseClicked(evt);
            }
        });
        selecionaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gerentesBox)
                                    .addComponent(caixasBox))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cozinheirosBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(auxiliarBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(selecionaTodos))))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 695, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerentesBox)
                    .addComponent(auxiliarBox)
                    .addComponent(selecionaTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixasBox)
                    .addComponent(cozinheirosBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerentesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerentesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerentesBoxActionPerformed

    private void cozinheirosBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cozinheirosBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cozinheirosBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) funcionariosTable.getModel();
        dtm.setRowCount(0);
        if(gerentesBox.isSelected()){
            this.listarGerentes(this.lojas);
        }
        if(caixasBox.isSelected()){
            this.listarCaixas(this.lojas);
        }
        if(auxiliarBox.isSelected()){
            this.listarAuxiliares(this.lojas);
        }
        if(cozinheirosBox.isSelected()){
            this.listarCozinheiros(this.lojas);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void selecionaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaTodosActionPerformed
        this.verificaSelecionarTodos();
    }//GEN-LAST:event_selecionaTodosActionPerformed

    private void selecionaTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecionaTodosMouseClicked
        this.verificaSelecionarTodos();
    }//GEN-LAST:event_selecionaTodosMouseClicked

    public void listarGerentes(ArrayList<Loja> lojas){
        String nomeloja;
        ArrayList<Gerente> gerentes;
        String [] linha = new String[5];
        DefaultTableModel dtm = (DefaultTableModel) funcionariosTable.getModel();
        for(Loja atual : lojas){
            nomeloja = BancoDeDados.recuperarNomeLoja(atual.getId_lanchonete());
            gerentes = BancoDeDados.gerentesDeUmaLoja(atual.getId_lanchonete());
            if(!gerentes.isEmpty()){
                for(Gerente g : gerentes){
                    linha[0] = g.getNome();
                    linha[1] = g.getTelefone();
                    linha[2] = g.getCpf();
                    linha[3] = nomeloja;
                    linha[4] = "Gerente";
                    dtm.addRow(linha);
                }
            }
        }
    }
    
    public void listarCaixas(ArrayList<Loja> lojas){
        String nomeloja;
        ArrayList<Caixa> caixas;
        String [] linha = new String[5];
        DefaultTableModel dtm = (DefaultTableModel) funcionariosTable.getModel();
        for(Loja atual : lojas){
            nomeloja = BancoDeDados.recuperarNomeLoja(atual.getId_lanchonete());
            caixas = BancoDeDados.caixasDeUmaLoja(atual.getId_lanchonete());
            if(!caixas.isEmpty()){
                for(Caixa c : caixas){
                    linha[0] = c.getNome();
                    linha[1] = c.getTelefone();
                    linha[2] = c.getCpf();
                    linha[3] = nomeloja;
                    linha[4] = "Caixa";
                    dtm.addRow(linha);
                }
            }
        }
    }
    
    public void listarAuxiliares(ArrayList<Loja> lojas){
        String nomeloja;
        ArrayList<Faxineiro> auxiliares;
        String [] linha = new String[5];
        DefaultTableModel dtm = (DefaultTableModel) funcionariosTable.getModel();
        for(Loja atual : lojas){
            nomeloja = BancoDeDados.recuperarNomeLoja(atual.getId_lanchonete());
            auxiliares = BancoDeDados.faxineirosDeUmaLoja(atual.getId_lanchonete());
            if(!auxiliares.isEmpty()){
                for(Faxineiro f : auxiliares){
                    linha[0] = f.getNome();
                    linha[1] = f.getTelefone();
                    linha[2] = f.getCpf();
                    linha[3] = nomeloja;
                    linha[4] = "Auxiliar de Limpeza";
                    dtm.addRow(linha);
                }
            }
        }
    }
    
    public void listarCozinheiros(ArrayList<Loja> lojas){
        String nomeloja;
        ArrayList<Cozinheiro> cozinheiros;
        String [] linha = new String[5];
        DefaultTableModel dtm = (DefaultTableModel) funcionariosTable.getModel();
        for(Loja atual : lojas){
            nomeloja = BancoDeDados.recuperarNomeLoja(atual.getId_lanchonete());
            cozinheiros = BancoDeDados.cozinheirosDeUmaLoja(atual.getId_lanchonete());
            if(!cozinheiros.isEmpty()){
                for(Cozinheiro c : cozinheiros){
                    linha[0] = c.getNome();
                    linha[1] = c.getTelefone();
                    linha[2] = c.getCpf();
                    linha[3] = nomeloja;
                    linha[4] = "Cozinheiro";
                    dtm.addRow(linha);
                }
            }
        }
    }
    
    public void selecionaTodos(boolean b){
        gerentesBox.setSelected(b);
        auxiliarBox.setSelected(b);
        caixasBox.setSelected(b);
        cozinheirosBox.setSelected(b);
    }
    
    public void verificaSelecionarTodos(){
        if(selecionaTodos.isSelected()){
            this.selecionaTodos(true);
        }
        else{
            this.selecionaTodos(false);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox auxiliarBox;
    private javax.swing.JCheckBox caixasBox;
    private javax.swing.JCheckBox cozinheirosBox;
    private javax.swing.JTable funcionariosTable;
    private javax.swing.JCheckBox gerentesBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton selecionaTodos;
    // End of variables declaration//GEN-END:variables
}
