/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDialogsAlteracaoDeDados;

import BancoDeDados.BancoDeDados;
import ClassesLojas.Loja;
import InterfaceMain.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author YiazmaT
 */
public class ModificarLanchonete extends javax.swing.JDialog {
    private Loja loja;
    private Main pai;
    /**
     * Creates new form ModificarLanchonete
     */
    public ModificarLanchonete(java.awt.Frame parent, boolean modal, Loja loja, Main pai) {
        super(parent, modal);
        initComponents();
        this.loja = loja;
        this.pai = pai;
        this.preencherDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        estadoField = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        cidadeField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        numField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        telefoneField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ruaField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bairroField = new javax.swing.JTextField();
        cepField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Dados Lanchonete");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shuffle (1).png"))); // NOI18N
        jButton1.setText("Alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            estadoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Estado:");

        cidadeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Cidade:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Número:");

        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Telefone:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shuffle (1).png"))); // NOI18N
        jLabel1.setText("Alterar Dados da Lanchonete");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Rua:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Bairro:");

        bairroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroFieldActionPerformed(evt);
            }
        });

        try {
            cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CEP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ruaField))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(bairroField)
                                                .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel13, jLabel3, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel12, jLabel8});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ruaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bairroField, cepField, cidadeField, estadoField, jLabel10, jLabel11, jLabel12, jLabel13, jLabel3, jLabel5, jLabel8, jLabel9, nomeField, numField, ruaField, telefoneField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //pegar e validar o nome da loja;
        String nome = nomeField.getText();
        if(nome.equals("")) {this.erro(1); return;}
        if(nome.length() > 50){this.erro(12); return;}
        nome = nome.toLowerCase();
        if(!nome.matches("([0-9a-zA-Z ]|â|à|ã|ä|á|Á|ê|ë|é|É|î|ï|í|Í|ô|õ|ö|ó|Ó|û|ü|ú|Ú|'|ç){1,50}")){this.erro(1); return;}
        nome = nome.toUpperCase();

        //pegar e validar telefone;
        String telefone = telefoneField.getText();
        if(telefone.contains(" ")) {erro(2); return;}

        //pegar e validar rua;
        String rua = ruaField.getText();
        if(rua.equals("")) {erro(4); return;}
        if(rua.length() > 100){this.erro(13); return;}
        if(!rua.matches("([a-zA-Z ]|â|à|ã|ä|á|Á|ê|ë|é|É|î|ï|í|Í|ô|õ|ö|ó|Ó|û|ü|ú|Ú|'|ç){1,50}")){this.erro(4); return;}

        //pegar e validar número;
        String n = numField.getText();
        if(n.equals("")) {erro(5); return;}
        if(!n.matches("[0-9]{1,10}")){this.erro(5); return;}
        int numero = Integer.parseInt(n);

        //pegar e validar bairro;
        String bairro = bairroField.getText();
        if(bairro.equals("")) {erro(6); return;}
        if(bairro.length() > 50){this.erro(14); return;}
        if(!bairro.matches("([a-zA-Z ]|â|à|ã|ä|á|Á|ê|ë|é|É|î|ï|í|Í|ô|õ|ö|ó|Ó|û|ü|ú|Ú|'|ç){1,50}")){this.erro(6); return;}

        //pegar e validar cidade;
        String cidade = cidadeField.getText();
        if(cidade.equals("")) {erro(7); return;}
        if(cidade.length() > 50){this.erro(15); return;}
        if(!cidade.matches("([a-zA-Z ]|â|à|ã|ä|á|Á|ê|ë|é|É|î|ï|í|Í|ô|õ|ö|ó|Ó|û|ü|ú|Ú|'|ç){1,50}")){this.erro(7); return;}

        //pegar e validar estado;
        String estado = estadoField.getText();
        if(estado.contains(" ")) {erro(8); return;}

        //pegar e validar cep;
        String cep = cepField.getText();
        if(cep.contains(" ")) {erro(9); return;}

        //verifica se ja existe uma loja com o mesmo nome;
        if(!this.loja.getNome().equals(nome)){
            if(BancoDeDados.verificaLojaComNomeIgual(nome, pai.getIdUsuarioLogado()) == true){
                this.erro(10);
                return;
            }
        }
 
        int confirm;
        confirm = JOptionPane.showConfirmDialog(null, "Deseja Realmente Alterar os Dados da Lanchonete para: "
                +"\nNome: "+nome
                +"\nTelefone: "+telefone
                +"\nRua: "+rua
                +"\nNúmero: "+numero
                +"\nBairro: "+bairro
                +"\nCidade: "+cidade
                +"\nCEP: "+cep
                +"\nEstado: "+estado
                , "Modificar Lanchonete", JOptionPane.YES_NO_OPTION);
        if(confirm == 0){
            BancoDeDados.updateLanchonete(nome, telefone, rua, numero, bairro, cidade, cep, estado, loja.getId_lanchonete());
        }
        else return;
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cidadeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeFieldActionPerformed

    private void bairroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroFieldActionPerformed

    private void erro(int e){
        switch(e){
            case 1: JOptionPane.showMessageDialog(null, "Nome Inválido!! Utilize apenas letras ou números."); break;
            case 2: JOptionPane.showMessageDialog(null, "Telefone Inválido!!"); break;
            case 3: JOptionPane.showMessageDialog(null, "CNPJ Inválido!!"); break;
            case 4: JOptionPane.showMessageDialog(null, "Rua Inválida!! Utilize apenas letras."); break;
            case 5: JOptionPane.showMessageDialog(null, "Número Inválido!! Utilize apenas números."); break;
            case 6: JOptionPane.showMessageDialog(null, "Bairro Inválido!! Utilize apenas letas."); break;
            case 7: JOptionPane.showMessageDialog(null, "Cidade Inválida!! Utilize apenas letas."); break;
            case 8: JOptionPane.showMessageDialog(null, "Estado Inválido!! Utilize apenas 2 letas."); break;
            case 9: JOptionPane.showMessageDialog(null, "CEP Inválido!! Utilize apenas números."); break;
            case 10: JOptionPane.showMessageDialog(null, "Já existe uma loja cadastrada com esse nome!!"); break;
            case 11: JOptionPane.showMessageDialog(null, "Já existe uma loja cadastrada com esse cnpj!!"); break;    
            case 12: JOptionPane.showMessageDialog(null, "Campo Nome pode ter no máximo 50 caracteres!!"); break;
            case 13: JOptionPane.showMessageDialog(null, "Campo Rua pode ter no máximo 100 caracteres!!"); break;
            case 14: JOptionPane.showMessageDialog(null, "Campo Bairro pode ter no máximo 50 caracteres!!"); break;    
            case 15: JOptionPane.showMessageDialog(null, "Campo Cidade pode ter no máximo 50 caracteres!!"); break;
        }
    }

    public void preencherDados(){
        nomeField.setText(loja.getNome());
        telefoneField.setText(loja.getTelefone());
        ruaField.setText(loja.getEndereco_rua());
        bairroField.setText(loja.getEndereco_bairro());
        cepField.setText(loja.getEndereco_cep());
        numField.setText(String.valueOf(loja.getEndereco_numero()));
        cidadeField.setText(loja.getEndereco_cidade());
        estadoField.setText(loja.getEndereco_estado());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroField;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JTextField cidadeField;
    private javax.swing.JFormattedTextField estadoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeField;
    private javax.swing.JTextField numField;
    private javax.swing.JTextField ruaField;
    private javax.swing.JFormattedTextField telefoneField;
    // End of variables declaration//GEN-END:variables
}
